# Generated by Django 4.1.1 on 2022-09-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skipped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('not_skipped', models.IntegerField()),
                ('no_pause_before_play', models.IntegerField()),
                ('context_type_user_collection', models.IntegerField()),
                ('hist_user_behavior_reason_start_fwdbtn', models.IntegerField()),
                ('hist_user_behavior_reason_start_trackdone', models.IntegerField()),
                ('hist_user_behavior_reason_end_backbtn', models.IntegerField()),
                ('hist_user_behavior_reason_end_fwdbtn', models.IntegerField()),
                ('hist_user_behavior_reason_end_trackdone', models.IntegerField()),
                ('mode_0', models.IntegerField()),
                ('week_day_Monday', models.IntegerField()),
            ],
        ),
    ]
