# Generated by Django 4.1.1 on 2022-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skipped',
            name='context_type_user_collection',
        ),
        migrations.RemoveField(
            model_name='skipped',
            name='hist_user_behavior_reason_end_backbtn',
        ),
        migrations.RemoveField(
            model_name='skipped',
            name='hist_user_behavior_reason_end_fwdbtn',
        ),
        migrations.RemoveField(
            model_name='skipped',
            name='hist_user_behavior_reason_end_trackdone',
        ),
        migrations.RemoveField(
            model_name='skipped',
            name='hist_user_behavior_reason_start_fwdbtn',
        ),
        migrations.RemoveField(
            model_name='skipped',
            name='hist_user_behavior_reason_start_trackdone',
        ),
        migrations.RemoveField(
            model_name='skipped',
            name='mode_0',
        ),
        migrations.RemoveField(
            model_name='skipped',
            name='not_skipped',
        ),
        migrations.RemoveField(
            model_name='skipped',
            name='sexe',
        ),
        migrations.RemoveField(
            model_name='skipped',
            name='week_day_Monday',
        ),
        migrations.AddField(
            model_name='skipped',
            name='context_type',
            field=models.CharField(choices=[('catalog', 'catalog'), ('charts', 'charts'), ('editorial playlist', 'editorial playlist'), ('personalized playlist', 'personalized playlist'), ('radio', 'radio'), ('user_collection', 'user_collection')], default='', max_length=35),
        ),
        migrations.AddField(
            model_name='skipped',
            name='hist_user_behavior_n_seekback',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skipped',
            name='hist_user_behavior_n_seekfwd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skipped',
            name='hist_user_behavior_reason_end',
            field=models.CharField(choices=[('backbtn', 'backbtn'), ('clickrow', 'clickrow'), ('endplay', 'endplay'), ('fwdbtn', 'fwdbtn'), ('logout', 'logout'), ('remote', 'remote'), ('trackdone', 'trackdone')], default='', max_length=35),
        ),
        migrations.AddField(
            model_name='skipped',
            name='hist_user_behavior_reason_start',
            field=models.CharField(choices=[('appload', 'appload'), ('backbtn', 'backbtn'), ('clickrow', 'clickrow'), ('clickrow', 'clickrow'), ('fwdbtn', 'fwdbtn'), ('playbtn', 'playbtn'), ('remote', 'remote'), ('trackdone', 'trackdone'), ('trackerror', 'trackerror')], default='', max_length=35),
        ),
        migrations.AddField(
            model_name='skipped',
            name='hour_of_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skipped',
            name='premium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skipped',
            name='session_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skipped',
            name='session_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skipped',
            name='track',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='skipped',
            name='week_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='skipped',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skipped',
            name='no_pause_before_play',
            field=models.IntegerField(default=0),
        ),
    ]
